// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Contexts
{
    using Configurations;
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    public class AdventureWorksOltpDatabase2012DbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<AdventureWorksOltpDatabase2012DbContext>
    {
        public AdventureWorksOltpDatabase2012DbContext Create()
        {
            return new AdventureWorksOltpDatabase2012DbContext();
        }
    }
}
// </auto-generated>
